export const MOCK_PLATFORM_ADMINS = [
  {
    id: 'padmin-1',
    name: 'Admin Plataforma',
    email: 'admin@plataforma.local',
    password: 'Admin@123',
    isActive: true,
  },
]

export const MOCK_USERS = [
  {
    id: 'user-admin',
    tenantId: 'tenant-1',
    tenantName: 'Acme Demo',
    name: 'Admin Demo',
    email: 'admin@demo.local',
    password: 'Admin@123',
    role: 'Admin',
    cpf: '',
    phone: '',
    department: 'TI',
    jobTitle: 'Administrador do Sistema',
    isActive: true,
    status: 'active',
    createdAt: '2024-01-10T08:00:00Z',
    notes: '',
  },
  {
    id: 'user-gestor',
    tenantId: 'tenant-1',
    tenantName: 'Acme Demo',
    name: 'Gestor Demo',
    email: 'gestor@demo.local',
    password: 'Admin@123',
    role: 'Gestor',
    cpf: '',
    phone: '',
    department: 'Operações',
    jobTitle: 'Gestor Operacional',
    isActive: true,
    status: 'active',
    createdAt: '2024-01-10T08:00:00Z',
    notes: '',
  },
  {
    id: 'user-1',
    tenantId: 'tenant-1',
    tenantName: 'Acme Demo',
    name: 'Carlos Mendes',
    email: 'carlos@acme.com',
    password: 'Admin@123',
    role: 'Operador',
    cpf: '123.456.789-00',
    phone: '(11) 99999-0001',
    department: 'Jurídico',
    jobTitle: 'Advogado Sênior',
    isActive: true,
    status: 'active',
    createdAt: '2024-01-15T08:00:00Z',
    notes: '',
  },
  {
    id: 'user-2',
    tenantId: 'tenant-1',
    tenantName: 'Acme Demo',
    name: 'Fernanda Oliveira',
    email: 'fernanda@acme.com',
    password: 'Admin@123',
    role: 'Operador',
    cpf: '234.567.890-00',
    phone: '(11) 99999-0002',
    department: 'Compras',
    jobTitle: 'Analista de Compras',
    isActive: true,
    status: 'active',
    createdAt: '2024-01-20T08:00:00Z',
    notes: '',
  },
  {
    id: 'user-3',
    tenantId: 'tenant-1',
    tenantName: 'Acme Demo',
    name: 'Ricardo Alves',
    email: 'ricardo@acme.com',
    password: 'Admin@123',
    role: 'Gestor',
    cpf: '345.678.901-00',
    phone: '(11) 99999-0003',
    department: 'Compras',
    jobTitle: 'Gerente de Compras',
    isActive: true,
    status: 'active',
    createdAt: '2024-02-01T08:00:00Z',
    notes: '',
  },
  {
    id: 'user-4',
    tenantId: 'tenant-1',
    tenantName: 'Acme Demo',
    name: 'Ana Paula Lima',
    email: 'ana@acme.com',
    password: 'Admin@123',
    role: 'Operador',
    cpf: '456.789.012-00',
    phone: '(11) 99999-0004',
    department: 'Financeiro',
    jobTitle: 'Controller',
    isActive: true,
    status: 'active',
    createdAt: '2024-02-10T08:00:00Z',
    notes: '',
  },
  {
    id: 'user-5',
    tenantId: 'tenant-1',
    tenantName: 'Acme Demo',
    name: 'Marcos Souza',
    email: 'marcos@acme.com',
    password: 'Admin@123',
    role: 'Operador',
    cpf: '567.890.123-00',
    phone: '(11) 99999-0005',
    department: 'RH',
    jobTitle: 'HRBP',
    isActive: true,
    status: 'active',
    createdAt: '2024-03-01T08:00:00Z',
    notes: '',
  },
]

export const MOCK_TENANT_MODULES = [
  { id: 'tm-1', tenantId: 'tenant-1', code: 'document_types', name: 'Tipos de Documento', isEnabled: true },
  { id: 'tm-2', tenantId: 'tenant-1', code: 'workflows',      name: 'Workflows',          isEnabled: true },
  { id: 'tm-3', tenantId: 'tenant-1', code: 'tasks',          name: 'Tarefas',            isEnabled: true },
  { id: 'tm-4', tenantId: 'tenant-1', code: 'organization',   name: 'Organização',        isEnabled: true },
  { id: 'tm-5', tenantId: 'tenant-1', code: 'metadata',       name: 'Metadados',          isEnabled: true },
  { id: 'tm-6', tenantId: 'tenant-1', code: 'users',          name: 'Usuários',           isEnabled: true },
]